kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: traefik-ingress-controller
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 443
      name: https