apiVersion: v1
kind: Service
metadata:
  name: traefik-admin
  namespace: traefik-ingress-controller
spec:
  ports:
    - protocol: TCP
      name: admin
      port: 8080
  selector:
    app: traefik
